# Generated by Django 4.0.4 on 2022-04-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('surname', models.CharField(default=None, max_length=225)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(default=None, max_length=255)),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='education_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('item', models.URLField(default=None, null=True, verbose_name='source of course item')),
                ('description', models.CharField(default=None, max_length=255, null=True)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('job_place', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255, null=True)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.item')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('surname', models.CharField(default=None, max_length=255)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('school', models.CharField(default=None, max_length=255)),
                ('grade', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.account')),
                ('group', models.ManyToManyField(blank=True, default=None, to='education_app.group')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_app.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(default=None, max_length=255)),
                ('time', models.TimeField(default=None)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_app.group')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=None)),
                ('was', models.BooleanField(default=None)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='education_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('document', models.TextField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.student')),
                ('tasks', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.task')),
            ],
        ),
    ]
