# Generated by Django 4.0.4 on 2022-04-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0002_group_course_alter_group_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='tasks',
            new_name='task',
        ),
    ]
