# Generated by Django 3.1.3 on 2022-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0003_rename_tasks_answer_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
