# Generated by Django 4.0.2 on 2022-05-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education_app', '0004_alter_employee_account_alter_student_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(blank=True, default=None, to='education_app.Group'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent',
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='education_app.Parent'),
        ),
        migrations.CreateModel(
            name='UnActiveStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('surname', models.CharField(default=None, max_length=255)),
                ('phone_number', models.CharField(default=None, max_length=15)),
                ('school', models.CharField(default=None, max_length=255)),
                ('grade', models.CharField(default=None, max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ManyToManyField(blank=True, default=None, to='education_app.Group')),
                ('parent', models.ManyToManyField(blank=True, default=None, null=True, to='education_app.Parent')),
            ],
        ),
    ]
