# Generated by Django 4.0.2 on 2022-05-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0005_alter_student_group_remove_student_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='education_app.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ManyToManyField(blank=True, default=None, to='education_app.Parent'),
        ),
        migrations.AlterField(
            model_name='unactivestudent',
            name='parent',
            field=models.ManyToManyField(blank=True, default=None, to='education_app.Parent'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='education_app.course')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='education_app.student')),
            ],
        ),
    ]
