# Generated by Django 4.0.2 on 2022-05-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0006_attendance_group_alter_student_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
