# Generated by Django 4.0.3 on 2022-05-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0007_attendance_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
